#!/bin/bash
#PBS -N Shallow_water
#PBS -l nodes=112
#PBS -l walltime=00:15:00
#PBS -q x6core
WDIR=/data4t/avolkov/Fortran/Shallow_Water/test/

cd $WDIR
# pwd
  mpiexec /data4t/avolkov/Fortran/Shallow_Water/test/a.out > time.txt
  

